# cmd: conda build . -c pacchem
package:
    name: projrot
    version: "1.3.2"

source:
    path: .

requirements:
    build:
        - cmake
        - {{ compiler('c') }}
    run:
        - cmake
        - {{ compiler('c') }}
