# cmd: conda build .
package:
    name: projrot
    version: "1.5.0"

source:
    path: .

requirements:
    build:
        - cmake
        - {{ compiler('c') }}
    run:
        - cmake
        - {{ compiler('c') }}
