# cmd: conda build . -c auto-mech
package:
    name: projrot
    version: "1.3.3"

source:
    path: .

requirements:
    build:
        - cmake
        - {{ compiler('c') }}
    run:
        - cmake
        - {{ compiler('c') }}
