# cmd: conda build . -c conda-forge
package:
    name: projrot
    version: "1.7.0"

source:
    path: .

requirements:
    build:
        - conda-forge::cmake=3.21.3
        - conda-forge::gcc_linux-64=11.2.0
    run:
        - conda-forge::cmake=3.21.3
        - conda-forge::gcc_linux-64=11.2.0
